#!/bin/bash
#
# MAMMON VPS Deployment Script
#
# Deploys MAMMON codebase to a VPS without any secrets.
# Secrets are injected at runtime via environment variables.
#
# Usage:
#   ./scripts/vps_deploy.sh user@hostname
#   ./scripts/vps_deploy.sh root@157.245.123.456
#
# Prerequisites:
#   - SSH access to VPS
#   - Python 3.11+ on VPS
#   - rsync installed locally
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
DEPLOY_DIR="/opt/mammon"
LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo -e "${GREEN}"
echo "=============================================="
echo "  MAMMON VPS Deployment"
echo "=============================================="
echo -e "${NC}"

# Check arguments
if [ $# -lt 1 ]; then
    echo "Usage: $0 user@hostname"
    echo ""
    echo "Example:"
    echo "  $0 root@157.245.123.456"
    echo "  $0 mammon@my-vps.digitalocean.com"
    exit 1
fi

VPS_HOST="$1"

echo -e "${BLUE}Deploying from: ${LOCAL_DIR}${NC}"
echo -e "${BLUE}Deploying to:   ${VPS_HOST}:${DEPLOY_DIR}${NC}"
echo ""

# Check rsync is available
if ! command -v rsync &> /dev/null; then
    echo -e "${RED}ERROR: rsync is required but not installed${NC}"
    exit 1
fi

# Check SSH connectivity
echo -e "${BLUE}Testing SSH connection...${NC}"
if ! ssh -o ConnectTimeout=10 "$VPS_HOST" "echo 'SSH OK'" &>/dev/null; then
    echo -e "${RED}ERROR: Cannot connect to ${VPS_HOST}${NC}"
    echo "Make sure you have SSH access configured."
    exit 1
fi
echo -e "${GREEN}SSH connection successful${NC}"

# Check Python version on VPS
echo -e "${BLUE}Checking Python version on VPS...${NC}"
PYTHON_VERSION=$(ssh "$VPS_HOST" "python3 --version 2>/dev/null || echo 'Not found'" | grep -oP '\d+\.\d+' | head -1)
if [[ -z "$PYTHON_VERSION" ]]; then
    echo -e "${RED}ERROR: Python 3 not found on VPS${NC}"
    echo "Install Python 3.11+: apt install python3.11 python3.11-venv"
    exit 1
fi
MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)
if [[ "$MAJOR" -lt 3 || ("$MAJOR" -eq 3 && "$MINOR" -lt 10) ]]; then
    echo -e "${YELLOW}WARNING: Python $PYTHON_VERSION may be too old. Recommended: 3.11+${NC}"
fi
echo -e "${GREEN}Python ${PYTHON_VERSION} found${NC}"

# Create deployment directory on VPS
echo -e "${BLUE}Creating deployment directory...${NC}"
ssh "$VPS_HOST" "sudo mkdir -p ${DEPLOY_DIR} && sudo chown \$(whoami) ${DEPLOY_DIR}"

# Sync code (excluding secrets and data)
echo -e "${BLUE}Syncing codebase (excluding secrets)...${NC}"
rsync -avz --progress \
    --exclude '.env' \
    --exclude '.env.*' \
    --exclude '*.db' \
    --exclude '*.sqlite' \
    --exclude '__pycache__' \
    --exclude '.pytest_cache' \
    --exclude '.mypy_cache' \
    --exclude '.git' \
    --exclude 'data/*.json' \
    --exclude 'data/*.log' \
    --exclude '*.log' \
    --exclude 'audit.log' \
    --exclude '.venv' \
    --exclude 'venv' \
    --exclude 'node_modules' \
    --exclude 'NEXT_SESSION*.md' \
    --exclude 'NEXT_SESSION*.txt' \
    --exclude 'htmlcov' \
    --exclude '.coverage' \
    "${LOCAL_DIR}/" "${VPS_HOST}:${DEPLOY_DIR}/"

echo -e "${GREEN}Code synced successfully${NC}"

# Install Poetry on VPS if not present
echo -e "${BLUE}Checking Poetry installation...${NC}"
if ! ssh "$VPS_HOST" "command -v poetry &>/dev/null"; then
    echo -e "${YELLOW}Installing Poetry on VPS...${NC}"
    ssh "$VPS_HOST" "curl -sSL https://install.python-poetry.org | python3 -"
    ssh "$VPS_HOST" "echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
fi
echo -e "${GREEN}Poetry available${NC}"

# Install dependencies
echo -e "${BLUE}Installing dependencies...${NC}"
ssh "$VPS_HOST" "cd ${DEPLOY_DIR} && ~/.local/bin/poetry install --no-dev --no-interaction"

# Create the .env template ONLY if one does not already exist. Never clobber a
# live .env — it holds real secrets (CDP creds, ALERT_WEBHOOK) that are not in
# git. To add new keys to an existing droplet, edit its .env by hand.
echo -e "${BLUE}Ensuring .env template...${NC}"
if ssh "$VPS_HOST" "test -f ${DEPLOY_DIR}/.env"; then
    echo -e "${YELLOW}Existing .env found on remote — leaving it untouched.${NC}"
    echo -e "${YELLOW}Add any new keys by hand (template is in scripts/vps_deploy.sh).${NC}"
else
ssh "$VPS_HOST" "cat > ${DEPLOY_DIR}/.env << 'ENVEOF'
# MAMMON VPS Configuration
# Generated by vps_deploy.sh on $(date)
#
# SECURITY: WALLET_SEED is injected at runtime - DO NOT ADD HERE
#

# Network Configuration
NETWORK=base-mainnet
BASE_RPC_URL=https://mainnet.base.org

# Database. Pin to data/ so the app, scripts/backup_db.py, and
# scripts/verify_positions.py all agree (the app default is repo-root mammon.db).
DATABASE_URL=sqlite:///data/mammon.db

# Safety Settings
DRY_RUN_MODE=false
WALLET_TIER=hot

# Wallet custody (WS7 CDP MPC). false = CDP MPC Server Wallet (no seed needed;
# creds below). true = local-seed custody (seed injected at runtime, never here).
USE_LOCAL_WALLET=false
CDP_ACCOUNT_NAME=mammon-hot
# Set to the funded MPC address to hard-fail startup on a wrong/empty account.
CDP_EXPECTED_ADDRESS=

# Tiered Wallet Limits (Tier 1: Hot Wallet)
HOT_WALLET_MAX_BALANCE_USD=2000
HOT_WALLET_MAX_TRANSACTION_USD=500
HOT_WALLET_DAILY_LIMIT_USD=1000
HOT_WALLET_AUTO_PAUSE=true

# Security Features
CONTRACT_WHITELIST_STRICT=true
EIP7702_DETECTION_ENABLED=true
PERMIT2_DETECTION_ENABLED=true

# Optimizer Settings (adjust as needed)
SCAN_INTERVAL_HOURS=2
MIN_APY_IMPROVEMENT=0.3
MIN_ANNUAL_GAIN_USD=1.0
MIN_PROFIT_USD=0.50
# Per-day rails for the 30-day Base run. Gas on Base is a fraction of a cent, so
# MAX_GAS_PER_DAY_USD is a runaway backstop (trips on a gas spike / loop bug),
# not a normal limiter; MAX_REBALANCES_PER_DAY is the churn rail. These now feed
# the scheduler's authoritative per-day gate.
MAX_REBALANCES_PER_DAY=24
MAX_GAS_PER_DAY_USD=2.0

# Spending Limits
MAX_TRANSACTION_VALUE_USD=500
DAILY_SPENDING_LIMIT_USD=1000
APPROVAL_THRESHOLD_USD=100

# API Keys (add your own)
ANTHROPIC_API_KEY=your_anthropic_key_here
CDP_API_KEY=your_cdp_key_here
CDP_API_SECRET=your_cdp_secret_here
CDP_WALLET_SECRET=your_wallet_secret_here

# Premium RPC (optional, recommended)
# ALCHEMY_API_KEY=your_alchemy_key
# PREMIUM_RPC_ENABLED=true
# PREMIUM_RPC_PERCENTAGE=100

# Chainlink Oracle
CHAINLINK_ENABLED=true
CHAINLINK_PRICE_NETWORK=base-mainnet

# Monitoring / alerting. Blank ALERT_WEBHOOK = push alerts DISABLED; set a
# Discord/Slack webhook so the heartbeat dead-man check, circuit-breaker trips,
# and stranded-funds alerts actually reach you during the 30-day run.
ALERT_WEBHOOK=
HEARTBEAT_FILE=data/heartbeat.json
HEARTBEAT_MAX_AGE_SECONDS=10800

# Circuit breaker (latching; persists to data/circuit_breaker_state.json).
# Resume after a trip with: python scripts/resume_optimizer.py --confirm
CIRCUIT_BREAKER_CONSECUTIVE_FAILURES=3
CIRCUIT_BREAKER_MAX_FAILURES_PER_DAY=10

# Logging
LOG_LEVEL=INFO
ENVIRONMENT=production
ENVEOF"
echo -e "${GREEN}.env template created${NC}"
fi

# Create data directory
ssh "$VPS_HOST" "mkdir -p ${DEPLOY_DIR}/data"

# Make scripts executable
ssh "$VPS_HOST" "chmod +x ${DEPLOY_DIR}/scripts/*.sh ${DEPLOY_DIR}/scripts/*.py 2>/dev/null || true"

# Print completion message
echo ""
echo -e "${GREEN}=============================================="
echo "  Deployment Complete!"
echo "==============================================${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. SSH to VPS and configure .env:"
echo -e "   ${BLUE}ssh ${VPS_HOST}${NC}"
echo -e "   ${BLUE}nano ${DEPLOY_DIR}/.env${NC}"
echo "   (Add your API keys, but NOT the wallet seed!)"
echo ""
echo "2. Generate a new wallet (if needed):"
echo -e "   ${BLUE}cd ${DEPLOY_DIR} && poetry run python scripts/generate_new_wallet.py${NC}"
echo "   (Write down the seed phrase securely!)"
echo ""
echo "3. Fund the new wallet on Base network:"
echo "   - Send ETH for gas (~\$10)"
echo "   - Send USDC for testing (~\$200-500)"
echo ""
echo "4. Start MAMMON with seed injection:"
echo -e "   ${BLUE}ssh ${VPS_HOST} \"MAMMON_WALLET_SEED='word1 word2 ... word12' ${DEPLOY_DIR}/scripts/vps_start.sh\"${NC}"
echo ""
echo "For persistent session (recommended):"
echo -e "   ${BLUE}ssh ${VPS_HOST}${NC}"
echo -e "   ${BLUE}screen -S mammon${NC}"
echo -e "   ${BLUE}MAMMON_WALLET_SEED='your seed' ${DEPLOY_DIR}/scripts/vps_start.sh${NC}"
echo "   (Press Ctrl+A, D to detach)"
echo ""
echo -e "${YELLOW}SECURITY REMINDERS:${NC}"
echo "- Never store seed phrase in files on VPS"
echo "- Never commit .env to git"
echo "- Use screen/tmux for persistent sessions"
echo "- Monitor audit.log for anomalies"
echo ""
